import { NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { z } from "zod";
import { requireMembership } from "@/lib/session";
import { getAdmin } from "@/lib/firebase-admin";

const collections: Record<string,string>={discuss:"channels",calendar:"calendarEvents",contacts:"contacts",sales:"salesOrders",pos:"posOrders",accounting:"invoices",purchase:"purchaseOrders",inventory:"products",manufacturing:"manufacturingOrders","shop-floor":"shopFloorOperations",barcode:"barcodeScans"};
const input=z.object({title:z.string().trim().min(2).max(160),subtitle:z.string().trim().max(240).default(""),status:z.string().trim().max(40).default("active"),amount:z.coerce.number().min(0).max(999999999).default(0),date:z.string().max(30).default("")});
export async function GET(_:Request,{params}:{params:Promise<{companyId:string;module:string}>}){const{companyId,module}=await params;const ctx=await requireMembership(companyId);if(!ctx)return NextResponse.json({error:"Forbidden"},{status:403});const collection=collections[module];if(!collection)return NextResponse.json({error:"Unsupported module"},{status:404});const snap=await getAdmin().db.collection(`companies/${companyId}/${collection}`).orderBy("createdAt","desc").limit(200).get();return NextResponse.json({records:snap.docs.map(d=>({id:d.id,...d.data(),createdAt:d.data().createdAt?.toDate?.()?.toISOString()??null}))})}
export async function POST(req:Request,{params}:{params:Promise<{companyId:string;module:string}>}){const{companyId,module}=await params;const ctx=await requireMembership(companyId);if(!ctx)return NextResponse.json({error:"Forbidden"},{status:403});const collection=collections[module];if(!collection)return NextResponse.json({error:"Unsupported module"},{status:404});try{const data=input.parse(await req.json());const ref=getAdmin().db.collection(`companies/${companyId}/${collection}`).doc();await ref.create({...data,companyId,createdBy:ctx.user.uid,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});return NextResponse.json({record:{id:ref.id,...data}},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Invalid record"},{status:400})}}
