import { NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { z } from "zod";
import { getAdmin } from "@/lib/firebase-admin";
import { appendAudit } from "@/lib/audit";
import { authorizeCompany, authorizationStatus, hasPermission, isCompanyAdministrator } from "@/lib/authorization";
import type { ModuleKey, PermissionKey } from "@/lib/types";

const modules: Partial<Record<ModuleKey,{collection:string;writePermission?:PermissionKey}>>={calendar:{collection:"calendarEvents"},contacts:{collection:"contacts",writePermission:"contacts.manage"},sales:{collection:"salesOrders",writePermission:"sales.manage"},pos:{collection:"posOrders"},accounting:{collection:"invoices"},purchase:{collection:"purchaseOrders"},inventory:{collection:"products"},manufacturing:{collection:"manufacturingOrders"},"shop-floor":{collection:"shopFloorOperations"},barcode:{collection:"barcodeScans"}};
const input=z.object({title:z.string().trim().min(2).max(160),subtitle:z.string().trim().max(240).default(""),status:z.string().trim().max(40).default("active"),amount:z.coerce.number().min(0).max(999999999).default(0),date:z.string().max(30).default("")});
export async function GET(_:Request,{params}:{params:Promise<{companyId:string;module:string}>}){const{companyId,module}=await params;const config=modules[module as ModuleKey];if(!config)return NextResponse.json({error:"Not found"},{status:404});const auth=await authorizeCompany(companyId,{module:module as ModuleKey});if(!auth.ok)return NextResponse.json({error:"Access denied"},{status:authorizationStatus(auth.reason)});const snap=await getAdmin().db.collection(`companies/${companyId}/${config.collection}`).orderBy("createdAt","desc").limit(200).get();return NextResponse.json({records:snap.docs.map(d=>({id:d.id,...d.data(),createdAt:d.data().createdAt?.toDate?.()?.toISOString()??null}))})}
export async function POST(req:Request,{params}:{params:Promise<{companyId:string;module:string}>}){const{companyId,module}=await params;const config=modules[module as ModuleKey];if(!config)return NextResponse.json({error:"Not found"},{status:404});const auth=await authorizeCompany(companyId,{module:module as ModuleKey});if(!auth.ok)return NextResponse.json({error:"Access denied"},{status:authorizationStatus(auth.reason)});if(config.writePermission?!hasPermission(auth.access.membership,config.writePermission):!isCompanyAdministrator(auth.access.membership))return NextResponse.json({error:"Access denied"},{status:403});try{const data=input.parse(await req.json());const db=getAdmin().db;const ref=db.collection(`companies/${companyId}/${config.collection}`).doc();const batch=db.batch();batch.create(ref,{...data,companyId,ownerId:auth.access.user.uid,createdBy:auth.access.user.uid,createdAt:FieldValue.serverTimestamp(),updatedBy:auth.access.user.uid,updatedAt:FieldValue.serverTimestamp()});appendAudit(db,companyId,{actorId:auth.access.user.uid,action:`${module}.record_created`,entityType:module,entityId:ref.id},batch);await batch.commit();return NextResponse.json({record:{id:ref.id,...data}},{status:201})}catch(e){return NextResponse.json({error:e instanceof z.ZodError?"Invalid request":"Could not create record"},{status:400})}}
